### ISSUE TITLE
Firefox pushing caret to new paragraph

### ISSUE THREAD

**Issue by fazil-imraan** [jkhaui/predictable#5]

**Comment by jkhaui** [comment]
Did you manage to fix this?

I haven't looked at predictable for a long time, but I'm planning to rewrite it to a basic MVP level over the coming weeks

**Comment by fazil-imraan** [comment]
i tried so many times but i can't.so Please help me to prevent the cursor
from break line after the suggestion.could you able to help me?

**Comment by fazil-imraan** [comment]
> Did you manage to fix this?
> 
> I haven't looked at predictable for a long time, but I'm planning to rewrite it to a basic MVP level over the coming weeks

i tried but there is no changes happened,could you able to help me out!!

**Comment by jkhaui** [comment]
> > Did you manage to fix this?
> > I haven't looked at predictable for a long time, but I'm planning to rewrite it to a basic MVP level over the coming weeks
> 
> i tried but there is no changes happened,could you able to help me out!!

Hey mate,
Sorry I've been very busy with work - I will take a look this weekend and update you
